version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '1235'
      POSTGRES_DB: ai_text_api
    ports:
      - "5432:5432"